# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Jason Park's blog
tagline:          
description:      '박준수의 GitBlog입니다!'
url:              https://essieng.github.io
baseurl:          https://essieng.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/Essieng
